baseURL = 'https://moxiaozi.com'  # 注意不要加末尾的斜杠
languageCode = 'zh-cn'
title = '我的博客'
theme = 'archie'

# 启用 Git 信息
enableGitInfo = true

# 时间格式设置
enableEmoji = true
hasCJKLanguage = true # 启用中文字数统计
defaultContentLanguage = "zh-cn"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# 确保生成 index.html
uglyURLs = false
relativeURLs = false

# 主题配置
[params]
    mode="auto"
    # mode="dark"
    useCDN=true
    subtitle = "个人博客"
    copyright = "© moxiaozi"
    author = "moxiaozi"  # 作者名称
    
    # 启用数学公式
    math = true
    katex = true
    
    # 访问统计配置
    busuanzi = true    # 启用不蒜子统计
    
    # 显示文章阅读时间
    showReadingTime = true
    
    # 时间显示配置
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"
    
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/xziguoux"

[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "文章"
url = "/posts"
weight = 2

[[menu.main]]
name = "关于"
url = "/about"
weight = 3
copyright = "© Athul"

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[markup]
  [markup.tableOfContents]
    startLevel = 1    # 从一级标题开始显示
    endLevel = 6      # 到六级标题结束
    ordered = false   # 使用无序列表
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许 HTML 标签
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"
