baseURL = 'https://moxiaozi.com'  # 注意不要加末尾的斜杠
languageCode = 'zh-cn'
title = '我的博客'
theme = 'archie'

# 确保生成 index.html
uglyURLs = false
relativeURLs = false

# 主题配置
[params]
    # mode="auto"
    mode="dark"
    useCDN=true
    subtitle = "个人博客"
    
    # 社交媒体链接
    social = [
        {name = "GitHub", type = "social", url = "https://github.com/xziguoux"},
        {name = "Twitter", type = "social", url = "https://twitter.com/xziguoux"}
    ]

[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "文章"
url = "/posts"
weight = 2

[[menu.main]]
name = "关于"
url = "/about"
weight = 3
